#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "code-server"
name = "code-server"
description.en = "Run VS Code on your server and access it in the browser"
description.fr = "Lancez VS Code sur votre serveur et accédez-y depuis votre navigateur"

version = "4.110.0~ynh1"

maintainers = ["Tagada"]

[upstream]
license = "MIT"
website = "https://coder.com"
admindoc = "https://coder.com/docs/code-server/latest"
userdoc = "https://coder.com/docs/code-server/latest/FAQ"
code = "https://github.com/coder/code-server"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = ["amd64", "arm64", "armhf"]
multi_instance = true

ldap = false
sso = false

disk = "500M"
ram.build = "50M"
ram.runtime = "100M"

[install]
    [install.domain]
    type = "domain"

    [install.admin]
    type = "user"

[resources]
    [resources.sources.main]
    amd64.url = "https://github.com/coder/code-server/releases/download/v4.110.0/code-server-4.110.0-linux-amd64.tar.gz"
    amd64.sha256 = "fa0698f37b51e1e3b22c511d54685bc698a0f5d8b7d4baa8b60de012faeba343"
    arm64.url = "https://github.com/coder/code-server/releases/download/v4.110.0/code-server-4.110.0-linux-arm64.tar.gz"
    arm64.sha256 = "750758e22164619ad0e33af63135ce4927c1b5a4cbafbce16ce9edde22557519"
    armhf.url = "https://github.com/coder/code-server/releases/download/v4.110.0/code-server-4.110.0-linux-armv7l.tar.gz"
    armhf.sha256 = "9e5d6388df9d2d6c5e4ce533da987d774a17d1e19dcee3fbe101923330620f8d"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.arm64 = "code-server-.*-linux-arm64.tar.gz"
    autoupdate.asset.amd64 = "code-server-.*-linux-amd64.tar.gz"
    autoupdate.asset.armhf = "code-server-.*-linux-armv7l.tar.gz"

    [resources.system_user]

    [resources.install_dir]
    dir = "/opt/yunohost/__APP__"

    [resources.data_dir]
    subdirs = ["user-data", "extensions"]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = "argon2"
