#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "code-server"
name = "code-server"
description.en = "Run VS Code on your server and access it in the browser"
description.fr = "Lancez VS Code sur votre serveur et accédez-y depuis votre navigateur"

version = "4.114.0~ynh1"

maintainers = ["Tagada"]

[upstream]
license = "MIT"
website = "https://coder.com"
admindoc = "https://coder.com/docs/code-server/latest"
userdoc = "https://coder.com/docs/code-server/latest/FAQ"
code = "https://github.com/coder/code-server"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = ["amd64", "arm64", "armhf"]
multi_instance = true

ldap = false
sso = false

disk = "500M"
ram.build = "50M"
ram.runtime = "100M"

[install]
    [install.domain]
    type = "domain"

    [install.admin]
    type = "user"

[resources]
    [resources.sources.main]
    amd64.url = "https://github.com/coder/code-server/releases/download/v4.114.0/code-server-4.114.0-linux-amd64.tar.gz"
    amd64.sha256 = "97e4e828e2252ec261b6cb427eb6f1cd16196aea4ca346d6d2d1a34c9c246d86"
    arm64.url = "https://github.com/coder/code-server/releases/download/v4.114.0/code-server-4.114.0-linux-arm64.tar.gz"
    arm64.sha256 = "ea917040a25881503ad314700b946f76b3bce9110c350b1f1cbbba6b8433ad47"
    armhf.url = "https://github.com/coder/code-server/releases/download/v4.114.0/code-server-4.114.0-linux-armv7l.tar.gz"
    armhf.sha256 = "5832b7f16f449ec7906fefeb0dc669be2b8ce25ce6aa2612cff4950ef4b358d7"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.arm64 = "code-server-.*-linux-arm64.tar.gz"
    autoupdate.asset.amd64 = "code-server-.*-linux-amd64.tar.gz"
    autoupdate.asset.armhf = "code-server-.*-linux-armv7l.tar.gz"

    [resources.system_user]

    [resources.install_dir]
    dir = "/opt/yunohost/__APP__"

    [resources.data_dir]
    subdirs = ["user-data", "extensions"]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = "argon2"
