#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "code-server"
name = "code-server"
description.en = "Run VS Code on your server and access it in the browser"
description.fr = "Lancez VS Code sur votre serveur et accédez-y depuis votre navigateur"

version = "4.118.0~ynh1"

maintainers = ["Tagada"]

[upstream]
license = "MIT"
website = "https://coder.com"
admindoc = "https://coder.com/docs/code-server/latest"
userdoc = "https://coder.com/docs/code-server/latest/FAQ"
code = "https://github.com/coder/code-server"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = ["amd64", "arm64", "armhf"]
multi_instance = true

ldap = false
sso = false

disk = "500M"
ram.build = "50M"
ram.runtime = "100M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/code"

    [install.admin]
    type = "user"

[resources]
    [resources.sources.main]
    amd64.url = "https://github.com/coder/code-server/releases/download/v4.118.0/code-server-4.118.0-linux-amd64.tar.gz"
    amd64.sha256 = "ab4dee01cacc20eb500c96660477d8ba755f69f402cc9cbab3a8496b4690f2fd"
    arm64.url = "https://github.com/coder/code-server/releases/download/v4.118.0/code-server-4.118.0-linux-arm64.tar.gz"
    arm64.sha256 = "70dd29a9bffa1ca7a9578e24106e612ee041192bf6aa5ece964b1af1e3d27c08"
    armhf.url = "https://github.com/coder/code-server/releases/download/v4.118.0/code-server-4.118.0-linux-armv7l.tar.gz"
    armhf.sha256 = "31e5701cb0d553f40aeab9a8603e8bcc9010e5b339d400402e0d08baaf594996"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.arm64 = "code-server-.*-linux-arm64.tar.gz"
    autoupdate.asset.amd64 = "code-server-.*-linux-amd64.tar.gz"
    autoupdate.asset.armhf = "code-server-.*-linux-armv7l.tar.gz"

    [resources.system_user]

    [resources.install_dir]
    dir = "/opt/yunohost/__APP__"

    [resources.data_dir]
    subdirs = ["user-data", "extensions"]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = "argon2"
