#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS
#=================================================

install_dir=$(ynh_app_setting_get --key=install_dir)

#=================================================
# SPECIFIC GETTERS FOR TOML SHORT KEY
#=================================================

get__password() {
    echo ""
}

get__enable_proposed_api() {
    echo "$(awk '/enable-proposed-api:/ {print $2}' $install_dir/config.yaml)"
}

# TODO: Write some getters and setters for __EXTENSIONS_GALLERY__ to go back to json directly

#=================================================
# SPECIFIC VALIDATORS FOR TOML SHORT KEYS
#=================================================

#=================================================
# SPECIFIC SETTERS FOR TOML SHORT KEYS
#=================================================

set__password() {
    if [ $password ]
    then
        salt=$(ynh_string_random)
        hashed_password=$(echo -n $password | argon2 $salt -id -e)

        sed -i "/hashed-password:.*/d" "$install_dir/config.yaml" || true

        echo "hashed-password: $hashed_password" >> "$install_dir/config.yaml"
        ynh_store_file_checksum "$install_dir/config.yaml"

        ynh_app_setting_set --key=hashed_password --value="$hashed_password"
    fi
}

set__enable_proposed_api() {
    sed -i "/enable-proposed-api:.*/d" "$install_dir/config.yaml"

    echo "enable-proposed-api: $enable_proposed_api" >> "$install_dir/config.yaml"
    ynh_store_file_checksum "$install_dir/config.yaml"

    ynh_app_setting_set --key=enable_proposed_api --value="$enable_proposed_api"
}

#=================================================
ynh_app_config_run "$1"
